version: '3'
 
services:
  otel-collector:
    container_name: invinsense-xdr-opentelemetry-collector
    image: otel/opentelemetry-collector-contrib:0.97.0
    volumes:
      - /home/ubuntu/otel-configration/config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the Collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
      - "55679:55679" # zpages extension
      - "9411:9411"
