openapi: "3.0.0"
info:
  title: Your API Title
  version: "1.0.0"
  description: Your API Description
  termsOfService: http://example.com/terms/
  contact:
    name: Your Name
    email: your.email@example.com
    url: http://example.com/contact/
  license:
    name: Your License
    url: http://example.com/license/
paths:
  /greeting/{name}:
    post:
      operationId: run.post_greeting
      responses:
        '200':
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
